version: '3'
services:
  app:
    image: poc-stream-processor-faust-avro
    depends_on:
      - kafka
    entrypoint: python -m src
    command: ["--check-host", "kafka:9092", "--check-host", "development"]
    environment:      
      - KAFKA_URL=kafka://kafka:9092
      - KAFKA_TOPIC=poc-stream-processor-faust-avro
      - SECRET={e2eaf0b2-dcb4-4531-85be-fcac8757142a}
    ports:
      - "8000:6066"
    volumes:
      - ./logs/app:/srv/app/logs

  zookeeper:  
    image: confluentinc/cp-zookeeper:3.2.0
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:3.2.0
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
